version: '3.8'

services:
  edgeprobe:
    image: ghcr.io/j0sh-neu/blockchain-rpc-edgeprobe:main
    container_name: blockchain-rpc-edgeprobe
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Mount a volume for persistent database storage
      - edgeprobe-data:/app/data
    environment:
      # Environment variables can be set here
      - TZ=UTC

volumes:
  # Define the volume for persistent data
  edgeprobe-data: