app = "blockchain-rpc-edgeprobe"
primary_region = "iad"
console_command = "/bin/bash"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "edgeprobe_data"
  destination = "/data"